[project]
name = "hello-vectordb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.5",
    "qdrant-client>=1.15.0",
    "sentence-transformers>=5.0.0",
]
